#undef CONFIG_WAKE_WORD
#define CONFIG_WAKE_WORD 0

#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define CHIP_NAME "ESP32"

// ========== AMP8315 V3 I2S功放输出 ==========
#define AUDIO_I2S_GPIO_BCLK     GPIO_NUM_26
#define AUDIO_I2S_GPIO_LRCK     GPIO_NUM_27
#define AUDIO_I2S_GPIO_DOUT     GPIO_NUM_25
#define AUDIO_I2S_GPIO_MCLK     I2S_GPIO_UNUSED

// ========== INMP441 I2S麦克风 ==========
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_22
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_21
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_19

#define BOARD_POWER_GPIO        GPIO_NUM_NC
#define BOARD_LED_GPIO          GPIO_NUM_NC
#define BOARD_BUTTON_GPIO       GPIO_NUM_0

#endif

